### PR TITLE
Support for io.js

### PR DESCRIPTION
**Pull request by ide**
- Added test case for a stack trace from io.js 2.3.0 (worked fine, didn't require changes)
- Added Travis configuration

### CODE REVIEW

**Comment by ide** [comment]
@Calamari are you interested in maintaining this repo? Wondering since there wasn't any feedback left on #1.

**Comment by ide** [comment]
@Calamari sorry to bother you -- could you take a look at this PR?

**Comment by ide** [comment]
@Calamari - ping

**Comment by Calamari** [comment]
Pong.. I am currently without notebook on vacation since bit over 2 weeks
and for one more week. But I will take a look directly afterwards.

**Comment by ide** [comment]
Cool. Thanks for the update =)

**Comment by ide** [comment]
Thanks! Could you publish a new release to npm?

**Pull request merged**
